### ISSUE TITLE
is this compatible with the FreeBSD's Zerotier port?

### ISSUE THREAD

**Issue by coreybrett** [ChanceM/pfSense-pkg-zerotier#1]
is this compatible with the FreeBSD's Zerotier port?

https://github.com/freebsd/freebsd-ports/tree/master/net/zerotier

**Comment by ChanceM** [comment]
@coreybrett Yes, actually it is essentially a front-end built for pfsense to interact with the zerotier port.

**Comment by coreybrett** [comment]
so would i install the zerotier package from freebsd, then build your package and install it?

**Comment by ChanceM** [comment]
I haven't worked on it in awhile due to losing my VM infrastructure at home. If you want to open issues I can take a look at them and see if I can help resolve them.

**Comment by coreybrett** [comment]
Great, i’m happy to provide VMs if that would help at all.

**Comment by coreybrett** [comment]
Any progress with this package?

**Comment by jmcphail** [comment]
Yes it was updated
