### ISSUE TITLE
the "Enable zerotier client and controller" option under Configuration does not work

### ISSUE THREAD

**Issue by coreybrett** [ChanceM/pfSense-pkg-zerotier#2]
The option to enable/disable the Zerotier service, does not work. Generates the following error message.
`Fatal error: Uncaught Error: Cannot unset string offsets in /usr/local/www/zerotier.php:52 Stack trace: #0 {main} thrown in /usr/local/www/zerotier.php on line 52 PHP ERROR: Type: 1, File: /usr/local/www/zerotier.php, Line: 52, Message: Uncaught Error: Cannot unset string offsets in /usr/local/www/zerotier.php:52 Stack trace: #0 {main} thrown`

**Comment by ChanceM** [comment]
Can you provide the output of `zerotier-one -v`?
This line is related to enabling the experimental features, rather than the package itself. I updated by pfSense VM to 2.4.4-RELEASE-p1 and build and installed zerotier-one version  1.2.12 and couldn't reproduce this. When I get some time I will try building a new pf VM and setup fresh.

**Comment by coreybrett** [comment]
`1.2.12`

I have the checkbox cleared right now,  but the Zerotier service is still running. When I try to check the box I get the above error message.

**Comment by tymiles003** [comment]
Team,
Was this ever resolved? Will this work with zerotier-one version 1.4.6?
Thanks

**Comment by jmcphail** [comment]
I just build and installed this version of the package, and it still has the reported issue above.  It's a bug, looking to resolve.  Its seems to work fine with 1.4.6, however.

**Comment by ChanceM** [comment]
@tymiles003 @jmcphail I got some time to work on the package this weekend. I have it running again, though it looks like some API calls changed. I was able to join a network and access the firewall from it. I'll try and push the updates this week.
