### ISSUE TITLE
No folder found

### ISSUE THREAD

**Issue by VanJaime5** [ChanceM/pfSense-pkg-zerotier#5]
On step 3 of yout build description the mentioned folder cannot be found
pfSense-pkg-zerotier
Where can I find the pfSense-pkg-zerotier-0.00.1.txz file?

**Comment by ChanceM** [comment]
You need to clone this repo into that folder path.

**Comment by bittix** [comment]
Hi.
What should I do after install package ?

**Comment by bittix** [comment]
I mean, I could Join a network but how can allow to use zero tier ip at pfsense firewall rules and NAT ?

**Comment by ChanceM** [comment]
> I mean, I could Join a network but how can allow to use zero tier ip at pfsense firewall rules and NAT ?

You can add the interface and assign it the ip from ZT. Then you can add firewall rules to that interface.

**Comment by bittix** [comment]
Hi @ChanceM , thanks for quick answer. 
Before I assign this interface I could, from pfsense console ping others hosts of my ZT network, but After Assign and force IP I just lost all communication, even going to Firewall Rules and allow all traffic of ZT interface.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/2783136/83327306-eae23c80-a250-11ea-816c-cd22c06e2dd8.png">

**Comment by ChanceM** [comment]
@bittix Okay, I just tested and that is consistent with my test setup. In my testing I was more interested in allowing other zerotier peers to access LAN resources behind the firewall. I will have to do some more testing for peer to peer communication.

**Comment by ChanceM** [comment]
@bittix Well an allow all rule or a ICMP allow rule allowed me to ping between my devices.

**Comment by FadyMakram-25** [comment]
On build steps
Run make clean ; make package
i get this error Makefile:49: *** missing separator. Stop.

**Comment by ChanceM** [comment]
> On build steps
> Run make clean ; make package
> i get this error Makefile:49: *** missing separator. Stop.

Sounds like spaces rather than tabs, did you modify the makefile?

**Comment by samcallen** [comment]
@ChanceM do you run git clone https://github.com/pfsense/FreeBSD-ports.git 
inside pfsense shell?

**Comment by ChanceM** [comment]
> @ChanceM do you run git clone https://github.com/pfsense/FreeBSD-ports.git 
> inside pfsense shell?

@samcallen no on the BSD box

**Comment by samcallen** [comment]
@ChanceM thanx👍
