### ISSUE TITLE
pfsense-pkg-zerotier (using it on pfsense)

### ISSUE THREAD

**Issue by samcallen** [ChanceM/pfSense-pkg-zerotier#6]
@ChanceM step 1 and step 2 done. from step 3 to 5, which files to copy to FreeBSD-ports/net/pfSense-pkg-zerotier and how do you do it?

**Comment by ChanceM** [comment]
So for step 3 Cline the repo into a folder under net. Step four go into the folder and build. The copy the product of the build to you pfsense box via scp.

**Comment by samcallen** [comment]
thanx
