### ISSUE TITLE
cant create controller and zt interface not showing

### ISSUE THREAD

**Issue by samcallen** [ChanceM/pfSense-pkg-zerotier#7]
@ChanceM hi, when i try to create a zerotier controller on pfsense and click save nothing is showing up to suggest a zt controller has been created. when i go to interfaces, ZT is also not showing. any help?

**Comment by ChanceM** [comment]
Per the Readme controller functionality is broken at this time. You can join a Network and an interface will be created but you must assign the IP manually.

**Comment by samcallen** [comment]
salute👍
