### ISSUE TITLE
Controller/access to webgui/ssh over zerotier

### ISSUE THREAD

**Issue by bvbek** [ChanceM/pfSense-pkg-zerotier#8]
HI.
Controller seams to be still not working. Is possible to create this "Controller functionality manualy"?

So I add my pfsense to existing network controls by ZeroTierOne.
I am able to ping everyone (phone, tablets, Laptops) however I am not able to ping over zero-tier network pfsense itself.
Any ssh/wegbui pfsense is not available over this zero-tier private network.
Any suggestion how to do it?

Edit: regarding access to pfsense server itself.
I found nice "how to" in opensense documentation.
https://docs.opnsense.org/manual/how-tos/zerotier.html

**Comment by ChanceM** [comment]
You will need appropriate firewall rules as well as a route added to
zerotier.

**Comment by bvbek** [comment]
Done. Everything is working awesome.
.
Thank you ChanceM for your amazing work.

Is any chance to restore/create "Controller" functionality mode on this pfsence machine or I should use some LXC/docker/VM solution to create independent from anybody  zerotier network ?
One more time thank you for everything.
